---
layout: cv
title: Jordan Moore's Resume
---
# Jordan Moore
Business Analytics major, Finance minor, and Firefighter/EMT

<div id="webaddress">
<a href="https://www.linkedin.com/in/jordan-moore-42b071171/">LinkedIn</a>


## Currently
Studying Business Analytics with a minor in Finance at BYU-I and working part-time as a Firefighter/EMT.
Data work for the Pioneer Baseball League and Madison Fire Department.

### Specialized in

Microsoft Excel, Python, Jupyter Notebook/QMDs, Power BI, Tableau, and MySQL.


### Research interests

Patterns and statistical correlation of certain events or relationships.


## Education

`2014-2017`
__Gov. John R. Rogers High School Puyallup, WA - High School Diploma__

`2015-2017`
__Pierce College Puyallup, WA - Associates of Arts__

`2019 - Present`
__Business Analytics major with Finance minor Rexburg, ID__



## Awards

`2017`
Eagle Scout

`2021` 
EMT of the Year FHFD

## Occupations

`2020-Present`
__Fremont County EMS__


`2020-2022`
__Teton County Fire and Rescue__


`2021-2023`
__Fort Hall Fire Department__


`2023-Present`
__Madison Fire Department__


